import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import { FRONTEND_TEXT as CORE_FRONTEND_TEXT } from "../custom_components/sv_dashboard/static/i18n-core.js";
const history=fs.readFileSync(new URL("../custom_components/sv_dashboard/server_history.py",import.meta.url),"utf8");
const sensor=fs.readFileSync(new URL("../custom_components/sv_dashboard/sensor.py",import.meta.url),"utf8");
const trip=fs.readFileSync(new URL("../custom_components/sv_dashboard/static/trip-history-card.js",import.meta.url),"utf8");
const fuelHistory=fs.readFileSync(new URL("../custom_components/sv_dashboard/static/fuel-history-card.js",import.meta.url),"utf8");
const dualHero=fs.readFileSync(new URL("../custom_components/sv_dashboard/static/dual-energy-overview-card.js",import.meta.url),"utf8");
const frontend=fs.readFileSync(new URL("../custom_components/sv_dashboard/static/frontend.js",import.meta.url),"utf8");
const strategy=fs.readFileSync(new URL("../custom_components/sv_dashboard/static/sv_dashboard.js",import.meta.url),"utf8");
const languages=["de","en","fr","it","es","pt","nl","da","nb","sv","fi","pl","cs","sk","hu","ro","sl","hr"];
test("canonical trips preserve independent fuel telemetry",()=>{assert.match(history,/_energy_entry\(raw\.get\("energyConsumptions"\), "Fuel"\)/);for(const key of ["fuel_level_start","fuel_level_end","fuel_range_start_km","fuel_range_end_km","fuel_consumption_l","fuel_consumption_l_100km","trip_type"]){assert.match(history,new RegExp(`"${key}"`));assert.match(sensor,new RegExp(`"${key}"`));}assert.match(history,/raw_fuel_consumption \/ 100/);});
test("existing trip history expands for hybrid data",()=>{assert.match(trip,/const hasFuel = trips\.some/);assert.match(trip,/l\/100 km/);assert.match(trip,/trip-type/);assert.match(trip,/dashboardText\.fuelRange/);assert.match(trip,/ev: "EV", hybrid: "Hybrid", ice: "ICE"/);});
test("dual-energy hero is wide, container-responsive and keeps missing fuel visible",()=>{assert.match(dualHero,/sv-dashboard-dual-energy-overview-card/);assert.match(dualHero,/grid-template-areas: "battery vehicle fuel"/);assert.match(dualHero,/container-type: inline-size/);assert.match(dualHero,/@container \(max-width: 760px\)/);assert.match(dualHero,/@container \(max-width: 430px\)/);assert.doesNotMatch(dualHero,/@media \(max-width:/);assert.match(dualHero,/getGridOptions\(\) \{ return \{ columns: 12, rows: 5, min_columns: 6, min_rows: 4 \}; \}/);assert.match(dualHero,/mapped\.fuel_autonomy/);assert.match(dualHero,/class="energy fuel"/);assert.match(dualHero,/fuelPercent === null \? "unavailable"/);assert.match(dualHero,/class="fill/);assert.match(dualHero,/max-height: 260px/);assert.doesNotMatch(dualHero,/Parkt|aktualisiert vor/);});
test("fuel history does not invent refill liters",()=>{assert.match(fuelHistory,/increase < minimum/);assert.match(fuelHistory,/fuel_refill_amount/);assert.doesNotMatch(fuelHistory,/fuel_consumption_total/);assert.match(fuelHistory,/event\.liters === null \? "—"/);});
test("new card strings cover 18 languages",()=>{for(const language of languages){assert.ok(CORE_FRONTEND_TEXT.dualEnergyOverview[language]);assert.ok(CORE_FRONTEND_TEXT.fuelHistory[language]);}});
test("frontend loads new cards and fuel history is capability gated",()=>{assert.match(frontend,/dual-energy-overview-card\.js\?v=0\.6\.0-beta\.5/);assert.match(frontend,/fuel-history-card\.js\?v=0\.6\.0-beta\.5/);assert.match(strategy,/modules\.trips && supportsFuel \? \{ type: "custom:sv-dashboard-fuel-history-card"/);});
